# Generated by Django 4.2.25 on 2025-10-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karniz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karniz',
                'verbose_name_plural': 'Karnizler',
            },
        ),
        migrations.CreateModel(
            name='Selpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Selpe',
                'verbose_name_plural': 'Selpeler',
            },
        ),
        migrations.AlterModelOptions(
            name='check',
            options={'verbose_name': 'Sargyt', 'verbose_name_plural': 'Sargytlar'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='color',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='color',
            name='price',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clienttype'),
        ),
        migrations.AddField(
            model_name='color',
            name='bez_ustanowka_TMT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='bez_ustanowka_USD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='diller_TMT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='diller_USD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='mary_diller_TMT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='mary_diller_USD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='mata_TMT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='mata_USD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
