# Generated by Django 4.2.25 on 2025-10-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_karniz_selpe_alter_check_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selpe',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
