# Generated by Django 4.2.25 on 2025-10-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_selpe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
