# Generated by Django 4.2.25 on 2025-10-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_color_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selpe',
            old_name='price',
            new_name='price_TMT',
        ),
        migrations.AddField(
            model_name='selpe',
            name='price_USD',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
