# Generated by Django 4.2.25 on 2025-10-22 02:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_price_selpe_price_tmt_selpe_price_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='client',
        ),
        migrations.RemoveField(
            model_name='check',
            name='price',
        ),
        migrations.RemoveField(
            model_name='check',
            name='status',
        ),
        migrations.AddField(
            model_name='check',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
