# Generated by Django 4.2.25 on 2025-11-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_check_client_remove_check_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='mary_diller_TMT',
        ),
        migrations.RemoveField(
            model_name='color',
            name='mary_diller_USD',
        ),
    ]
