# Generated by Django 4.2.25 on 2025-12-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_color_mary_diller_tmt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='total_meter_square',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
